---
- name: enable sensu-client to survive reboot
  service: name=sensu-client enabled=yes
  sudo: true

- name: generate /etc/sensu/conf.d/client.json
  template:
    src=sensu.client.json.j2
    dest=/etc/sensu/conf.d/client.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  notify: restart sensu client
  sudo: true

- name: copy all the checks files
  synchronize:
    src=files/sensu/plugins/
    dest=/etc/sensu/plugins/
    mode=0750
  sudo: true
  sudo_user: sensu
  notify:
    - set checks to sensu
    - restart sensu client
  tags:
    - update_checks
  sudo: true
