---

- name: Ensure Ruby is installed
  apt: name={{ item }} state=latest
  sudo: true
  with_items:
    - ruby
    - ruby-dev
    - ruby-pg
    - build-essential

- name: Install Required Ruby Gems
  gem: name={{ item }} executable=gem1.9.1 state=latest user_install=no
  sudo: true
  with_items:
    - json
    - sensu-plugin
    - net-ping
    - mixlib-cli
    - rest_client
    - bunny

- name: add the official Sensu repository's key
  apt_key: url=http://repos.sensuapp.org/apt/pubkey.gpg state=present
  sudo: true

- name: add the official Sensu repository
  copy:
    src=sensu-server.list
    dest=/etc/apt/sources.list.d/
    backup=yes
  register: aptrepo
  sudo: true

- name: refresh apt cache
  apt: update_cache=yes
  when: aptrepo.changed
  sudo: true

- name: install sensu
  apt: name=sensu state=present
  sudo: true

- name: set which Ruby to use
  lineinfile:
    dest=/etc/default/sensu
    regexp=^EMBEDDED_RUBY=
    line=EMBEDDED_RUBY={{ sensu_server_embedded_ruby }}
  sudo: true

- name: create the SSL directory
  file:
    path=/etc/sensu/ssl
    owner=sensu
    group=sensu
    mode=0750
    state=directory
  sudo: true

- name: copy the SSL certificate & key
  copy:
    src=files/sensu_{{ item }}.pem
    dest=/etc/sensu/ssl/{{ item }}.pem
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  sudo: true
  with_items:
    - client_cert
    - client_key

- name: generate /etc/sensu/config.json
  template:
    src=sensu.config.json.j2
    dest=/etc/sensu/config.json
    owner=sensu
    group=sensu
    mode=0640
    backup=yes
  sudo: true
  notify:
    - restart sensu server
    - restart sensu client