project_path = "../savings_champion/resources/"
http_path = "/static/"
css_dir = "css"
images_dir = "img"
javascripts_dir = "js"
relative_assets = true
line_comments = false
#output_style = :nested #:expanded or :nested or :compact or :compressed
sourcemap = true