from django.conf.urls import patterns, url

uuid_re = r'[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}'
intorfloat_re = r"(\d+(?:\.\d+)?)"

urlpatterns = patterns('concierge.views',

                       url(r'^$', 'landing.index', name='concierge_landing'),
                       url(r'^user/(?P<uuid>\d+)/$', 'landing.index', name='concierge_landing'),
                       url(r'^stage/one/user/(?P<uuid>\d+)/$', 'landing.stage_one', name='concierge_landing_stage_one'),
                       url(r'^stage/one/async/$', 'landing.stage_one_async', name='concierge_landing_stage_one_async'),
                       url(r'^stage/two/user/(?P<uuid>\d+)/$', 'landing.stage_two', name='concierge_landing_stage_two'),
                       url(r'^stage/two/async/$', 'landing.stage_two_async', name='concierge_landing_stage_two_async'),

                       url(r'^personal-savings-account-calculator/$', 'landing.personal_index',
                           name='concierge_personal_landing'),
                       url(r'^personal-savings-account-calculator/user/(?P<uuid>\d+)/$', 'landing.personal_index',
                           name='concierge_personal_landing'),
                       url(r'^personal-savings-account-calculator/stage/one/user/(?P<uuid>\d+)/$',
                           'landing.personal_stage_one', name='concierge_personal_landing_stage_one'),
                       url(r'^personal-savings-account-calculator/stage/one/async/$',
                           'landing.personal_stage_one_async', name='concierge_personal_landing_stage_one_async'),
                       url(r'^personal-savings-account-calculator/stage/two/user/(?P<uuid>\d+)/$',
                           'landing.personal_stage_two', name='concierge_personal_landing_stage_two'),
                       url(r'^personal-savings-account-calculator/stage/two/async/$',
                           'landing.personal_stage_two_async', name='concierge_personal_landing_stage_two_async'),

                       url(r'^business-savings-account-calculator/$', 'landing.business_index',
                           name='concierge_business_landing'),
                       url(r'^business-savings-account-calculator/user/(?P<uuid>\d+)/$', 'landing.business_index',
                           name='concierge_business_landing'),
                       url(r'^business-savings-account-calculator/stage/one/user/(?P<uuid>\d+)/$',
                           'landing.business_stage_one', name='concierge_business_landing_stage_one'),
                       url(r'^business-savings-account-calculator/stage/one/async/$',
                           'landing.business_stage_one_async', name='concierge_business_landing_stage_one_async'),
                       url(r'^business-savings-account-calculator/stage/two/user/(?P<uuid>\d+)/$',
                           'landing.business_stage_two', name='concierge_business_landing_stage_two'),
                       url(r'^business-savings-account-calculator/stage/two/async/$',
                           'landing.business_stage_two_async', name='concierge_business_landing_stage_two_async'),

                       url(r'^savings-account-calculator/$', 'landing.full_tool_index',
                           name='concierge_full_tool_landing'),
                       url(r'^savings-account-calculator/user/(?P<uuid>\d+)/$', 'landing.full_tool_index',
                           name='concierge_full_tool_landing'),
                       url(r'^savings-account-calculator/stage/one/user/(?P<uuid>\d+)/$',
                           'landing.full_tool_stage_one', name='concierge_full_tool_landing_stage_one'),
                       url(r'^savings-account-calculator/stage/one/async/$',
                           'landing.full_tool_stage_one_async', name='concierge_full_tool_landing_stage_one_async'),
                       url(r'^savings-account-calculator/stage/two/user/(?P<uuid>\d+)/$',
                           'landing.full_tool_stage_two', name='concierge_full_tool_landing_stage_two'),
                       url(r'^savings-account-calculator/stage/two/async/$',
                           'landing.full_tool_stage_two_async', name='concierge_full_tool_landing_stage_two_async'),
                       url(r'^savings-account-calculator/stage/two/user/(?P<uuid>\d+)/thank_you/$',
                           'landing.full_tool_stage_two_thank_you', name='concierge_full_tool_landing_stage_two_thank_you'),

                       url(r'^numberline/(?P<minimum>' + intorfloat_re + ')/(?P<maximum>' + intorfloat_re + ')/$',
                           'landing.numberline', name='concierge_landing_numberline'),

                       url(r'^adviser/$', 'adviser.adviser_dashboard', name='adviser_dashboard'),
                       url(r'^adviser/ajax/claim/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_claim_client_ajax', name='adviser_claim_client'),
                       url(r'^adviser/ajax/fake/(?P<enquiry_id>' + uuid_re + ')/$', 'adviser.adviser_fake_client_ajax',
                           name='adviser_fake_client'),
                       url(r'^adviser/ajax/contacted/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_contacted_client_ajax', name='adviser_contacted_client'),
                       url(r'^adviser/ajax/no-contact/(?P<enquiry_id>' + uuid_re + ')/(?P<stage>\d+)/$',
                           'adviser.adviser_no_contact_client_ajax',
                           name='adviser_no_contact_client'),
                       url(r'^adviser/ajax/signed/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_signed_client_ajax', name='adviser_signed_client'),
                       url(r'^adviser/ajax/fact-find/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_fact_find_client_ajax', name='adviser_fact_find_client'),
                       url(r'^adviser/ajax/illustrated/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_illustrated_client_ajax', name='adviser_illustrated_client'),
                       url(r'^adviser/ajax/recommended/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_recommended_client_ajax',
                           name='adviser_recommendation_client'),
                       url(r'^adviser/ajax/unsuitable/(?P<enquiry_id>' + uuid_re + ')/$',
                           'adviser.adviser_unsuitable_client_ajax',
                           name='adviser_unsuitable_client'),

                       url(r'^adviser/ajax/add/client/$', 'adviser.adviser_add_client_ajax', name='adviser_add_client'),

                       url(r'^adviser/ajax/statistics/$', 'adviser.adviser_statistics_ajax', name='adviser_statistics'),
                       url(r'^adviser/ajax/leads/personal/$', 'adviser.adviser_personal_leads_ajax',
                           name='adviser_personal_leads'),
                       url(r'^adviser/ajax/leads/unclaimed/$', 'adviser.adviser_unclaimed_leads_ajax',
                           name='adviser_unclaimed_leads'),
                       url(r'^adviser/ajax/leads/recent/$', 'adviser.adviser_recent_leads_ajax',
                           name='adviser_recent_leads'),
                       url(r'^adviser/ajax/leads/recent/name/(?P<name>.*)/$', 'adviser.adviser_recent_leads_ajax',
                           name='adviser_recent_leads'),
                       url(r'^adviser/ajax/leads/recent/email/(?P<email>.*)/$', 'adviser.adviser_recent_leads_ajax',
                           name='adviser_recent_leads'),
                       url(r'^adviser/ajax/leads/recent/phone/(?P<phone>.*)/$', 'adviser.adviser_recent_leads_ajax',
                           name='adviser_recent_leads'),

                       url(r'^adviser/client/(?P<client_id>' + uuid_re + ')/$', 'client.adviser_client_dashboard',
                           name='adviser_client_dashboard'),
                       url(r'^adviser/ajax/client/edit/notes/$', 'client.adviser_client_notes',
                           name='adviser_client_notes'),
                       url(r'^adviser/ajax/client/(?P<client_id>\d+)/edit/', 'client.update_client_details',
                           name='update_client_details'),

                       url(r'^management/$', 'management.management_dashboard', name='management_dashboard'),
                       url(r'^management/ajax/statistics/$', 'management.management_statistics_ajax',
                           name='management_statistics'),
                       url(r'^management/ajax/advisers/workload/$', 'management.management_adviser_workload_ajax',
                           name='management_adviser_workload'),
                       url(r'^management/ajax/source/pipeline/$', 'management.management_source_pipeline_ajax',
                           name='management_source_pipeline'),
                       url(r'^management/ajax/statistics/reasons/$', 'management.management_adviser_reason',
                           name='management_adviser_reason'),
                       url(r'^management/ajax/adviser/timing/$', 'management.management_adviser_timing_ajax',
                           name='management_adviser_timing'),

                       url(r'^engine/$', 'engine.engine_index', name='engine_index'),
                       url(r'^engine/(?P<email>[^@]+@[^@]+\.[^@]+)/$', 'engine.engine_index', name='engine_index'),
                       url(r'^engine/ajax/user/load/$', 'engine.engine_load_user', name='engine_load_user'),
                       url(r'^engine/ajax/user/load/(?P<email>.+)/$', 'engine.engine_load_user',
                           name='engine_load_user'),
                       url(r'^engine/ajax/user/update/(?P<concierge_user_id>' + uuid_re + ')/$',
                           'engine.engine_update_user', name='engine_update_user'),
                       url(r'^engine/ajax/user/update/(?P<concierge_user_id>' + uuid_re + ')/pool/create/$',
                           'engine.engine_create_pool', name='engine_create_pool'),
                       url(r'^engine/ajax/user/update/pool/update/$', 'engine.engine_update_pool',
                           name='engine_update_pool'),
                       url(r'^engine/ajax/user/update/pool/update/user/(?P<user>' + uuid_re + ')/$',
                           'engine.engine_update_pool', name='engine_update_pool'),
                       url(r'^engine/ajax/user/(?P<concierge_user_id>' + uuid_re + ')/pools/$',
                           'engine.engine_get_pool', name='engine_get_pool'),

                       url(r'^engine/ajax/user/process/(?P<concierge_user_id>' + uuid_re + ')/$',
                           'engine.engine_process_user',
                           name='engine_process_user'),
                       url(r'^engine/ajax/user/process/(?P<concierge_user_id>' + uuid_re + ')/best_case/$',
                           'engine.engine_process_user',
                           kwargs={'best_case': True}, name='engine_process_user_best_case'),

                       url(r'^engine/ajax/user/update/product/required/$',
                           'engine.engine_get_required_products',
                           name='engine_get_required_products'),
                       url(r'^engine/ajax/user/update/product/required/add/$',
                           'engine.engine_require_product',
                           name='engine_require_product'),
                       url(r'^engine/ajax/user/update/product/required/remove/$',
                           'engine.engine_removed_required_product',
                           name='engine_removed_required_product'),

                       url(
                           r'^engine/ajax/user/update/product/removed/$',
                           'engine.engine_get_removed_products',
                           name='engine_get_removed_products'),
                       url(
                           r'^engine/ajax/user/update/product/removed/add/$',
                           'engine.engine_remove_product',
                           name='engine_remove_product'),
                       url(
                           r'^engine/ajax/user/update/product/removed/remove/$',
                           'engine.engine_restore_product',
                           name='engine_restore_product'),

                       url(
                           r'^engine/ajax/user/update/product/allowed/$',
                           'engine.engine_get_allowed_products',
                           name='engine_get_allowed_products'),
                       url(
                           r'^engine/ajax/user/update/product/allowed/add/$',
                           'engine.engine_allow_product',
                           name='engine_allow_product'),
                       url(
                           r'^engine/ajax/user/update/product/allowed/remove/$',
                           'engine.engine_remove_allowed_product',
                           name='engine_remove_allowed_product'),

                       url(r'engine/ajax/master_products/provider/$', 'engine.engine_get_master_products_from_provider',
                           name='engine_get_master_products_from_provider'),
                       url(r'engine/ajax/products/provider/$', 'engine.engine_get_products_from_provider',
                           name='engine_get_products_from_provider'),

                       url(r'engine/ajax/user/product/existing/delete/(?P<product_portfolio_id>\d+)/$',
                           'engine.engine_delete_existing_products', name='engine_delete_existing_products'),
                       url(r'engine/ajax/user/product/existing/delete/fixed/(?P<product_portfolio_id>\d+)/$',
                           'engine.engine_delete_existing_fixed_term_products',
                           name='engine_delete_existing_fixed_term_products'),

                       url(r'engine/ajax/user/product/existing/$', 'engine.engine_get_existing_products',
                           name='engine_get_existing_products'),

                       url(r'engine/ajax/user/product/existing/add/$', 'engine.engine_add_existing_product',
                           name='engine_add_existing_product'),

                       url(r'wizard/(?P<client_id>' + uuid_re + ')/$', 'wizard.concierge_wizard',
                           name='concierge_wizard'),
                       url(r'this_is_money/widget/$', 'landing.this_is_money_concierge_widget', name="this_is_money_concierge_widget"),
                       )


